version: '3'
services:
  gateway:
    image: dfw/gateway
    ports:
      - "4000:4000"
    deploy:
      replicas: 1
    networks:
      - webnet
    environment:
      - FRONT_END_HOST=http://frontend:3000
      - LISTING_HOST=http://listingserver:5000
  frontend:
    image : dfw/frontend
    ports:
      - "3000:3000"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - webnet
  listingserver:
    image: dfw/listingserver
    depends_on:
      - redis
    ports:
      - "5000:5000"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    environment:
      - REDIS_HOST=redis
      - MONGO_AUTH=dfw:dfw123
    networks:
      - webnet
  websocket:
    image : dfw/websocketserver
    depends_on:
      - redis
    ports:
      - "6000:6000"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - webnet
    environment:
      - REDIS_HOST=redis
  redis:
    image : redis:5.0.4
    ports:
      - "6379:6379"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
    
  # zookeeper:
  #   image: wurstmeister/zookeeper
  #   ports:
  #     - "2181:2181"
  #   networks:
  #     - webnet
  # kafka:
  #   image : wurstmeister/kafka
  #   ports:
  #     - "9092:9092"
    # environment:
    #   KAFKA_ADVERTISED_HOST_NAME: localhost
    #   KAFKA_ADVERTISED_PORT: "9092"
    #   KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    # networks:
    #   - webnet
networks:
  webnet: